version: '3.7'

volumes:
  influxdb_data:
  node-red-data:
  grafana_data:
  mosquitto_data:
  mosquitto_config:

networks:
  broker-adapter-network:
    driver: overlay
  adapter-db-network:
    driver: overlay
  grafana-db-network:
    driver: overlay

services:
  influxdb:
    image: influxdb:1.7
    deploy:
      replicas: 3
    environment:
      - INFLUXDB_DB=iot_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user_password
      - organisation=UPB
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - adapter-db-network
      - grafana-db-network

  grafana:
    image: grafana-server
    deploy:
      replicas: 1
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2023
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - "80:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/logs.txt:/data/logs.txt
    networks:
      - grafana-db-network
    depends_on:
      - influxdb
      - mosquitto

  mosquitto:
    image: mosquitto-server
    deploy:
      replicas: 3
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config
    networks:
      - broker-adapter-network

  node-red:
    image: node-red-client
    deploy:
      replicas: 1
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Bucharest
      - DEBUG_DATA_FLOW=true
      - MQTT_BROKER_ADDRESS=sprc3_mosquitto
    volumes:
      - ./node-red:/data
    networks:
      - broker-adapter-network
      - adapter-db-network
    depends_on:
      - influxdb
      - mosquitto

  mqtt-client:
    image: mqtt-client-image
    deploy:
      replicas: 9
    environment:
      - MQTT_BROKER_ADDRESS=sprc3_mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_SUBSCRIBE_TOPIC=tema3-sprc
      - MQTT_PUBLISH_TOPIC=tema3-sprc
      - MQTT_CLIENT_ID=MQTT_Client
      - SERVER_PORT=6000
    networks:
      - broker-adapter-network
    depends_on:
      - influxdb
      - mosquitto