FROM grafana/grafana:latest

# Copy your script into the container
COPY grafana/init.sh /usr/share/grafana/init.sh

# Set the script as the entry point
ENTRYPOINT ["/bin/bash", "/usr/share/grafana/init.sh"]