# Dockerfile
FROM python:3.8-slim

WORKDIR /app

COPY mqtt-client/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip --no-cache-dir -r requirements.txt

EXPOSE 6000

COPY . /app

CMD ["python", "mqtt-client/mqtt-client.py"]